import type { Client } from "./types"

export const clientsData: Client[] = [
  {
    id: "1",
    name: "RTS",
    logoUrl: "/rts-logo.jpg",
    category: "Media",
    status: "active",
    products: ["Mobile App", "Pchella", "TTS"],
    website: "https://rts.rs",
    assignedTo: "John Smith",
    nextAction: "Schedule Q1 review meeting",
    nextActionDate: "2026-02-15",
    contacts: [{ id: "c1", name: "Marko Petrović", email: "marko@rts.rs", role: "Technical Director" }],
    todos: [
      { id: "t1", text: "Review mobile app analytics", completed: false },
      { id: "t2", text: "Prepare feature roadmap", completed: false },
    ],
    notes: "Key client with long-term contract. Interested in expanding to additional products.",
    activity: [
      { id: "a1", comment: "Deployed new mobile app update", date: "2026-01-05" },
      { id: "a2", comment: "Monthly check-in completed", date: "2025-12-20" },
    ],
  },
  {
    id: "2",
    name: "Telegraf",
    logoUrl: "/telegraf-logo.jpg",
    category: "Media",
    status: "active",
    products: ["Mobile App", "Pchella", "TTS", "Komentari"],
    website: "https://telegraf.rs",
    assignedTo: "Sarah Johnson",
    nextAction: "Follow up on Komentari feedback",
    nextActionDate: "2026-01-20",
    contacts: [{ id: "c2", name: "Ana Jovanović", email: "ana@telegraf.rs", role: "Product Manager" }],
    todos: [
      { id: "t3", text: "Implement requested comment moderation features", completed: true },
      { id: "t4", text: "Schedule training session", completed: false },
    ],
    notes: "Heavy user of Komentari system. Requests frequent updates and improvements.",
    activity: [{ id: "a3", comment: "Added new moderation rules", date: "2026-01-08" }],
  },
  {
    id: "3",
    name: "HRT",
    logoUrl: "/hrt-logo.jpg",
    category: "Media",
    status: "active",
    products: ["Mobile App", "Pchella", "TTS"],
    website: "https://hrt.hr",
    assignedTo: "John Smith",
    nextAction: "Discuss contract renewal",
    nextActionDate: "2026-03-01",
    contacts: [{ id: "c3", name: "Ivan Horvat", email: "ivan@hrt.hr", role: "CTO" }],
    todos: [{ id: "t5", text: "Prepare contract renewal proposal", completed: false }],
    notes: "Contract expires in Q1. Very satisfied with current services.",
    activity: [{ id: "a4", comment: "Quarterly business review completed", date: "2025-12-15" }],
  },
  {
    id: "4",
    name: "Politika",
    logoUrl: "/politika-logo.jpg",
    category: "Media",
    status: "active",
    products: ["Mobile App", "Pchella"],
    website: "https://politika.rs",
    assignedTo: "Michael Chen",
    nextAction: "Present TTS demo",
    nextActionDate: "2026-01-25",
    contacts: [{ id: "c4", name: "Jelena Nikolić", email: "jelena@politika.rs", role: "Editor-in-Chief" }],
    todos: [
      { id: "t6", text: "Prepare TTS presentation materials", completed: false },
      { id: "t7", text: "Schedule demo call", completed: true },
    ],
    notes: "Interested in adding TTS to their product suite. Legacy client since 2020.",
    activity: [{ id: "a5", comment: "Initial TTS interest expressed", date: "2026-01-04" }],
  },
  {
    id: "5",
    name: "Danas",
    logoUrl: "/danas-logo.jpg",
    category: "Media",
    status: "active",
    products: ["Mobile App", "Pchella", "CMS", "TTS", "Komentari", "e-Kiosk"],
    website: "https://danas.rs",
    assignedTo: "Sarah Johnson",
    nextAction: "Monthly sync meeting",
    nextActionDate: "2026-01-30",
    contacts: [
      { id: "c5", name: "Stefan Milošević", email: "stefan@danas.rs", role: "Head of Digital" },
      { id: "c6", name: "Milica Popović", email: "milica@danas.rs", role: "Technical Lead" },
    ],
    todos: [
      { id: "t8", text: "Review e-Kiosk performance metrics", completed: false },
      { id: "t9", text: "Optimize CMS workflow", completed: false },
    ],
    notes: "Our most comprehensive client using all products. Strong relationship and regular feedback loop.",
    activity: [
      { id: "a6", comment: "e-Kiosk rollout completed successfully", date: "2026-01-06" },
      { id: "a7", comment: "CMS training session delivered", date: "2025-12-18" },
    ],
  },
  {
    id: "6",
    name: "Panathinaikos FC",
    logoUrl: "/panathinaikos-fc-logo.jpg",
    category: "Sport",
    status: "active",
    products: ["Litteraworks", "Pchella"],
    website: "https://pao.gr",
    assignedTo: "Emma Williams",
    nextAction: "Review season statistics integration",
    nextActionDate: "2026-02-10",
    contacts: [{ id: "c7", name: "Nikos Papadopoulos", email: "nikos@pao.gr", role: "Digital Manager" }],
    todos: [{ id: "t10", text: "Add new player statistics module", completed: false }],
    notes: "Using Litteraworks for match reports and fan engagement. Very tech-forward organization.",
    activity: [{ id: "a8", comment: "Mid-season review completed", date: "2025-12-22" }],
  },
  {
    id: "7",
    name: "ESAKE",
    logoUrl: "/esake-logo.jpg",
    category: "Sport",
    status: "pending",
    products: [],
    website: "https://esake.gr",
    assignedTo: "Michael Chen",
    nextAction: "Send initial proposal",
    nextActionDate: "2026-01-18",
    contacts: [{ id: "c8", name: "Dimitris Kostopoulos", email: "dimitris@esake.gr", role: "Operations Director" }],
    todos: [
      { id: "t11", text: "Prepare customized proposal", completed: false },
      { id: "t12", text: "Research their current tech stack", completed: true },
    ],
    notes: "Greek basketball league. Interested in comprehensive digital solution. High potential deal.",
    activity: [{ id: "a9", comment: "Initial discovery call completed", date: "2026-01-10" }],
  },
  {
    id: "8",
    name: "Cedevita Olimpija",
    logoUrl: "/cedevita-olimpija-logo.jpg",
    category: "Sport",
    status: "pending",
    products: [],
    website: "https://cedevitaolimpija.com",
    assignedTo: "Emma Williams",
    nextAction: "Follow up on proposal",
    nextActionDate: "2026-01-22",
    contacts: [{ id: "c9", name: "Luka Novak", email: "luka@cedevitaolimpija.com", role: "Marketing Director" }],
    todos: [{ id: "t13", text: "Address questions from proposal meeting", completed: false }],
    notes: "Slovenian basketball club. Waiting for budget approval. Decision expected end of January.",
    activity: [
      { id: "a10", comment: "Proposal sent", date: "2026-01-12" },
      { id: "a11", comment: "Product demo conducted", date: "2026-01-08" },
    ],
  },
  {
    id: "9",
    name: "FK Partizan",
    logoUrl: "/fk-partizan-logo.jpg",
    category: "Sport",
    status: "active",
    products: ["Pchella"],
    website: "https://partizan.rs",
    assignedTo: "John Smith",
    nextAction: "Discuss expansion opportunities",
    nextActionDate: "2026-02-05",
    contacts: [{ id: "c10", name: "Nikola Đorđević", email: "nikola@partizan.rs", role: "Media Manager" }],
    todos: [{ id: "t14", text: "Prepare mobile app pitch", completed: false }],
    notes: "Currently using only Pchella. Good upsell opportunity for Mobile App and Litteraworks.",
    activity: [{ id: "a12", comment: "Pchella performance review - excellent engagement", date: "2025-12-28" }],
  },
  {
    id: "10",
    name: "AS Roma",
    logoUrl: "/as-roma-logo.jpg",
    category: "Sport",
    status: "active",
    products: ["Pchella"],
    website: "https://asroma.com",
    assignedTo: "Emma Williams",
    nextAction: "Quarterly business review",
    nextActionDate: "2026-02-20",
    contacts: [
      { id: "c11", name: "Marco Rossi", email: "marco@asroma.com", role: "Head of Digital Content" },
      { id: "c12", name: "Giulia Ferrari", email: "giulia@asroma.com", role: "Technical Coordinator" },
    ],
    todos: [
      { id: "t15", text: "Prepare Q4 analytics report", completed: true },
      { id: "t16", text: "Schedule QBR presentation", completed: false },
    ],
    notes: "Premium Serie A client. Excellent reference for European market expansion. High visibility partnership.",
    activity: [
      { id: "a13", comment: "Successfully handled Champions League traffic spike", date: "2026-01-07" },
      { id: "a14", comment: "Seasonal content strategy workshop delivered", date: "2025-12-10" },
    ],
  },
]
